#ifndef __SORTING_HPP
#define __SORTING_HPP

#include "bitonic_sort.hpp"
#include "bubble_sort.hpp"
#include "bucket_sort.hpp"
#include "cartesiantree_sort.hpp"
#include "coctail_sort.hpp"
#include "comb_sort.hpp"
#include "counting_sort.hpp"
#include "cycle_sort.hpp"
#include "gnome_sort.hpp"
#include "heap_sort.hpp"
#include "insertion_sort.hpp"
#include "merge_sort.hpp"
#include "oddeven_sort.hpp"
#include "pancake_sort.hpp"
#include "permutation_sort.hpp"
#include "pigeonhole_sort.hpp"
#include "quick_sort.hpp"
#include "radix_sort.hpp"
#include "selection_sort.hpp"
#include "shell_sort.hpp"
#include "sleep_sort.hpp"
#include "stooge_sort.hpp"
#include "strand_sort.hpp"
#include "structure_sort.hpp"
#include "tag_sort.hpp"
#include "tim_sort.hpp"
#include "tree_sort.hpp"

#endif
